# Generated by Django 2.1.5 on 2019-02-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_rules', '0003_auto_20190209_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametype',
            name='questions_settings',
        ),
    ]
