# Generated by Django 2.1.5 on 2019-02-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_rules', '0004_remove_gametype_questions_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametype',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
