# Generated by Django 2.1.5 on 2019-02-22 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_rules', '0007_answer_next'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='next',
        ),
        migrations.AlterField(
            model_name='answer',
            name='next_poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_poll', to='game_rules.Poll'),
        ),
    ]
