# Generated by Django 2.1.4 on 2019-02-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_rules', '0002_auto_20190122_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametype',
            name='polls_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], help_text='Select poll type from the available types', max_length=30),
        ),
    ]
