# Generated by Django 2.1.5 on 2019-02-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190210_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
