# Generated by Django 2.1.5 on 2019-02-21 10:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_game_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.PositiveIntegerField()),
                ('game_type', models.PositiveIntegerField()),
                ('vote', models.CharField(max_length=150)),
                ('points', models.SmallIntegerField(default=0)),
                ('poll', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='polls_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='votelog',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Game'),
        ),
    ]
