# Generated by Django 2.1.5 on 2019-02-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_game_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.PositiveIntegerField()),
                ('game', models.PositiveIntegerField()),
                ('vote', models.CharField(max_length=150)),
                ('points', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
