# Generated by Django 2.1.5 on 2019-02-18 20:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_votelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='polls_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
    ]
