# Generated by Django 2.1.5 on 2019-02-21 10:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190221_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='answered_polls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
    ]
